#!/usr/bin/env python

from enum import Enum


class ConfigConsts:
	DOME9_ACCESS_ID = 'DOME9_ACCESS_ID'
	DOME9_SECRET_KEY = 'DOME9_SECRET_KEY'
	DEFAULT_FORMAT = 'application/json'
	DEFAULT_BASE_URL = 'https://api.dome9.com/v2/'
	DEFAULT_LOG_LEVEL = 'INFO'
	DEFAULT_LOGGER_ROTATION = '100 MB'


class LoggerConsts:
	LOG_LEVEL = 'LOG_LEVEL'
	LOG_FILE_PATH = 'LOG_FILE_PATH'


class RequestMethods:
	GET = 'get'
	POST = 'post'
	PATCH = 'patch'
	PUT = 'put'
	DELETE = 'delete'


class AwsRegions(Enum):
	OREGON = 'us-west-2'
	NORTH_CALIFORNIA = 'us-west-1'
	OHIO = 'us-east-2'
	NORTH_VIRGINIA = 'us-east-1'
	MUMBAI = 'ap-south-1'
	SEOUL = 'ap-northeast-2'
	SINGAPORE = 'ap-southeast-1'
	SYDNEY = 'ap-southeast-2'
	TOKYO = 'ap-northeast-1'
	CANADA = 'ca-central-1'
	FRANKFURT = 'eu-central-1'
	IRELAND = 'eu-west-1'
	LONDON = 'eu-west-2'
	PARIS = 'eu-west-3'
	# HONG_KONG        = 'ap-east-1'  # known bug (the security token included in the request is invalid)
	STOCKHOLM = 'eu-north-1'
	SAO_PAULO = 'sa-east-1'


class OperationModes(Enum):
	READ = 'Read'
	MANAGED = 'Managed'


class ProtectionModes(Enum):
	FULL_MANAGE = 'FullManage'
	READ_ONLY = 'ReadOnly'


class CloudAccountTypes(Enum):
	AWS = 'Aws'
	AZURE = 'Azure'
	GOOGLE = 'Google'
	KUBERNETES = 'Kubernetes'


class NewGroupBehaviors(Enum):
	READ_ONLY = 'ReadOnly'
	FULL_MANAGE = 'FullManage'
	RESET = 'Reset'


class CloudVendors(Enum):
	AWS = 'aws'
	AZURE = 'azure'
	GOOGLE = 'google'
	KUBERNETES = 'kubernetes'


class Protocols(Enum):
	ALL = 'ALL'
	HOPOPT = 'HOPOPT'
	ICMP = 'ICMP'
	IGMP = 'IGMP'
	GGP = 'GGP'
	IPV4 = 'IPV4'
	ST = 'ST'
	TCP = 'TCP'
	CBT = 'CBT'
	EGP = 'EGP'
	IGP = 'IGP'
	BBN_RCC_MON = 'BBN_RCC_MON'
	NVP2 = 'NVP2'
	PUP = 'PUP'
	ARGUS = 'ARGUS'
	EMCON = 'EMCON'
	XNET = 'XNET'
	CHAOS = 'CHAOS'
	UDP = 'UDP'
	MUX = 'MUX'
	DCN_MEAS = 'DCN_MEAS'
	HMP = 'HMP'
	PRM = 'PRM'
	XNS_IDP = 'XNS_IDP'
	TRUNK1 = 'TRUNK1'
	TRUNK2 = 'TRUNK2'
	LEAF1 = 'LEAF1'
	LEAF2 = 'LEAF2'
	RDP = 'RDP'
	IRTP = 'IRTP'
	ISO_TP4 = 'ISO_TP4'
	NETBLT = 'NETBLT'
	MFE_NSP = 'MFE_NSP'
	MERIT_INP = 'MERIT_INP'
	DCCP = 'DCCP'
	ThreePC = 'ThreePC'
	IDPR = 'IDPR'
	XTP = 'XTP'
	DDP = 'DDP'
	IDPR_CMTP = 'IDPR_CMTP'
	TP_PLUS_PLUS = 'TPplusplus'
	IL = 'IL'
	IPV6 = 'IPV6'
	SDRP = 'SDRP'
	IPV6_ROUTE = 'IPV6_ROUTE'
	IPV6_FRAG = 'IPV6_FRAG'
	IDRP = 'IDRP'
	RSVP = 'RSVP'
	GRE = 'GRE'
	DSR = 'DSR'
	BNA = 'BNA'
	ESP = 'ESP'
	AH = 'AH'
	I_NLSP = 'I_NLSP'
	SWIPE = 'SWIPE'
	NARP = 'NARP'
	MOBILE = 'MOBILE'
	TLSP = 'TLSP'
	SKIP = 'SKIP'
	ICMPV6 = 'ICMPV6'
	IPV6_NONXT = 'IPV6_NONXT'
	IPV6_OPTS = 'IPV6_OPTS'
	CFTP = 'CFTP'
	SAT_EXPAK = 'SAT_EXPAK'
	KRYPTOLAN = 'KRYPTOLAN'
	RVD = 'RVD'
	IPPC = 'IPPC'
	SAT_MON = 'SAT_MON'
	VISA = 'VISA'
	IPCV = 'IPCV'
	CPNX = 'CPNX'
	CPHB = 'CPHB'
	WSN = 'WSN'
	PVP = 'PVP'
	BR_SAT_MON = 'BR_SAT_MON'
	SUN_ND = 'SUN_ND'
	WB_MON = 'WB_MON'
	WB_EXPAK = 'WB_EXPAK'
	ISO_IP = 'ISO_IP'
	VMTP = 'VMTP'
	SECURE_VMTP = 'SECURE_VMTP'
	VINES = 'VINES'
	TTP = 'TTP'
	NSFNET_IGP = 'NSFNET_IGP'
	DGP = 'DGP'
	TCF = 'TCF'
	EIGRP = 'EIGRP'
	OSPFIGP = 'OSPFIGP'
	SPRITE_RPC = 'SPRITE_RPC'
	LARP = 'LARP'
	MTP = 'MTP'
	AX25 = 'AX25'
	IPIP = 'IPIP'
	MICP = 'MICP'
	SCC_SP = 'SCC_SP'
	ETHERIP = 'ETHERIP'
	ENCAP = 'ENCAP'
	GMTP = 'GMTP'
	IFMP = 'IFMP'
	PNNI = 'PNNI'
	PIM = 'PIM'
	ARIS = 'ARIS'
	SCPS = 'SCPS'
	QNX = 'QNX'
	AN = 'AN'
	IPCOMP = 'IPCOMP'
	SNP = 'SNP'
	COMPAQ_PEER = 'COMPAQ_PEER'
	IPX_IN_IP = 'IPX_IN_IP'
	VRRP = 'VRRP'
	PGM = 'PGM'
	L2TP = 'L2TP'
	DDX = 'DDX'
	IATP = 'IATP'
	STP = 'STP'
	SRP = 'SRP'
	UTI = 'UTI'
	SMP = 'SMP'
	SM = 'SM'
	PTP = 'PTP'
	ISIS = 'ISIS'
	FIRE = 'FIRE'
	CRTP = 'CRTP'
	CRUDP = 'CRUDP'
	SSCOPMCE = 'SSCOPMCE'
	IPLT = 'IPLT'
	SPS = 'SPS'
	PIPE = 'PIPE'
	SCTP = 'SCTP'
	FC = 'FC'
	RSVP_E2E_IGNORE = 'RSVP_E2E_IGNORE'
	MOBILITY_HEADER = 'MOBILITY_HEADER'
	UDPLITE = 'UDPLITE'
	MPLS_IN_IP = 'MPLS_IN_IP'
	MANET = 'MANET'
	HIP = 'HIP'
	SHIM6 = 'SHIM6'
	WESP = 'WESP'
	ROHC = 'ROHC'
